<a href="https://colab.research.google.com/github/Seomzo/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [16]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import tensorflow as tf
# from tensorflow.keras.models import Model
# from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [17]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [18]:
# Create y_df with the Attrition and Department columns
y_dep_df = attrition_df[['Department']]
y_att_df = attrition_df[['Attrition']]

y_dep_df.head()

               Department
0                   Sales
1  Research & Development
2  Research & Development
3  Research & Development
4  Research & Development

In [19]:
# Create a list of at least 10 column names to use as X data
X_columns = ['Education', 'DistanceFromHome', 'Age', 'JobSatisfaction', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsSinceLastPromotion', 'YearsAtCompany', 'NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[X_columns]

# Show the data types for X_df
X_df.dtypes

Education                   int64
DistanceFromHome            int64
Age                         int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsSinceLastPromotion     int64
YearsAtCompany              int64
NumCompaniesWorked          int64
dtype: object

In [20]:
# Convert OverTime to a numeric value
X_df['OverTime'] = X_df['OverTime'].map({'Yes': 1, 'No': 0})
X_df.dtypes

<ipython-input-20-8159bbe899d6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['OverTime'] = X_df['OverTime'].map({'Yes': 1, 'No': 0})

Education                  int64
DistanceFromHome           int64
Age                        int64
JobSatisfaction            int64
OverTime                   int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsSinceLastPromotion    int64
YearsAtCompany             int64
NumCompaniesWorked         int64
dtype: object

In [21]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_att_train, y_att_test, y_dep_train, y_dep_test = train_test_split(X_df, y_att_df,y_dep_df)

In [22]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dep_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
dep_encoded = dep_encoder.fit_transform(y_dep_df)
dep_columns = dep_encoder.get_feature_names_out()
dep_encoded_df = pd.DataFrame(dep_encoded, columns=dep_columns)
# Create two new variables by applying the encoder
# to the training and testing data
encoded_y_dep_train = dep_encoder.fit_transform(y_dep_train)
encoded_y_dep_test = dep_encoder.fit_transform(y_dep_test)

dep_encoded_df.head()
print(encoded_y_dep_train)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]

In [24]:
# Create a OneHotEncoder for the Attrition column
att_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
att_encoder.fit(y_att_train)

# Create two new variables by applying the encoder
# to the training and testing data
encoded_y_att_train = att_encoder.transform(y_att_train)
encoded_y_att_test = att_encoder.transform(y_att_test)

encoded_y_att_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [25]:
# Find the number of columns in the X training data.
num_cols = len(X_train.columns)

# Create the input layer
input_layer = tf.keras.layers.Input(shape=(num_cols,), name='input_layer')

# Create at least two shared layers
shared_layer_1 = tf.keras.layers.Dense(units=10, activation='relu')(input_layer)
shared_layer_2 = tf.keras.layers.Dense(units=10, activation='relu')(shared_layer_1)

In [26]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
hidden_layer = tf.keras.layers.Dense(units=10, activation='relu')(shared_layer_2)

# Create the output layer
dep_output = tf.keras.layers.Dense(units=3, activation='softmax',name='department_output')(hidden_layer)

In [27]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
hidden_layer2 = tf.keras.layers.Dense(units=10, activation='relu')(shared_layer_2)

# Create the output layer
attrition_output = tf.keras.layers.Dense(units=2, activation='sigmoid',name='attrition_output')(hidden_layer2)

In [28]:
# Create the model
model = tf.keras.models.Model(inputs=input_layer, outputs=[dep_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics={'department_output':'accuracy', 'attrition_output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_5 (Dense)           │ (None, 10)             │            110 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_6 (Dense)           │ (None, 10)             │            110 │ dense_5[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_7 (Dense)           │ (None, 10)             │            110 │ dense_6[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_8 (Dense)           │ (None, 10)             │            110 │ dense_6[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             33 │ dense_7[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             22 │ dense_8[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 495 (1.93 KB)

 Trainable params: 495 (1.93 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
# Train the model
fit_model = model.fit(X_train_scaled, {'department_output': encoded_y_dep_train, 'attrition_output': encoded_y_att_train}, epochs=100, batch_size=32, validation_split=0.2)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - attrition_output_accuracy: 0.3081 - attrition_output_loss: 0.7720 - department_output_accuracy: 0.0492 - department_output_loss: 1.3272 - loss: 2.0994 - val_attrition_output_accuracy: 0.5701 - val_attrition_output_loss: 0.7035 - val_department_output_accuracy: 0.2805 - val_department_output_loss: 1.1194 - val_loss: 1.8224
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.6372 - attrition_output_loss: 0.6890 - department_output_accuracy: 0.4076 - department_output_loss: 1.0791 - loss: 1.7682 - val_attrition_output_accuracy: 0.8235 - val_attrition_output_loss: 0.6336 - val_department_output_accuracy: 0.6244 - val_department_output_loss: 0.9907 - val_loss: 1.6237
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8328 - attrition_output_loss: 0.6313 - department_output_accuracy: 0.6384 - department_output_loss: 0.9660 - loss: 1.5974 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.5683 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.9108 - val_loss: 1.4782
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8526 - attrition_output_loss: 0.5615 - department_output_accuracy: 0.6617 - department_output_loss: 0.8878 - loss: 1.4493 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.5024 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8547 - val_loss: 1.3557
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8580 - attrition_output_loss: 0.5026 - department_output_accuracy: 0.6684 - department_output_loss: 0.8240 - loss: 1.3266 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4571 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8242 - val_loss: 1.2792
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8614 - attrition_output_loss: 0.4552 - department_output_accuracy: 0.6403 - department_output_loss: 0.8269 - loss: 1.2823 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4343 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8108 - val_loss: 1.2427
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8552 - attrition_output_loss: 0.4418 - department_output_accuracy: 0.6407 - department_output_loss: 0.8037 - loss: 1.2457 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4228 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8056 - val_loss: 1.2257
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8449 - attrition_output_loss: 0.4432 - department_output_accuracy: 0.6221 - department_output_loss: 0.8156 - loss: 1.2591 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4145 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8033 - val_loss: 1.2150
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8364 - attrition_output_loss: 0.4406 - department_output_accuracy: 0.6494 - department_output_loss: 0.7876 - loss: 1.2284 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4094 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8025 - val_loss: 1.2090
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8421 - attrition_output_loss: 0.4166 - department_output_accuracy: 0.6601 - department_output_loss: 0.7712 - loss: 1.1875 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4047 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8023 - val_loss: 1.2042
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8560 - attrition_output_loss: 0.3942 - department_output_accuracy: 0.6637 - department_output_loss: 0.7556 - loss: 1.1492 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4003 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8017 - val_loss: 1.1993
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8579 - attrition_output_loss: 0.3814 - department_output_accuracy: 0.6688 - department_output_loss: 0.7683 - loss: 1.1494 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3957 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8017 - val_loss: 1.1948
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8490 - attrition_output_loss: 0.3932 - department_output_accuracy: 0.6534 - department_output_loss: 0.7773 - loss: 1.1704 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3937 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8003 - val_loss: 1.1916
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8526 - attrition_output_loss: 0.3914 - department_output_accuracy: 0.6443 - department_output_loss: 0.7785 - loss: 1.1701 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3902 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8002 - val_loss: 1.1880
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8329 - attrition_output_loss: 0.3987 - department_output_accuracy: 0.6788 - department_output_loss: 0.7399 - loss: 1.1380 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3876 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8001 - val_loss: 1.1854
Epoch 16/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8446 - attrition_output_loss: 0.3959 - department_output_accuracy: 0.6722 - department_output_loss: 0.7466 - loss: 1.1427 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3860 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7983 - val_loss: 1.1821
Epoch 17/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8487 - attrition_output_loss: 0.3723 - department_output_accuracy: 0.6394 - department_output_loss: 0.7996 - loss: 1.1720 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3852 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7979 - val_loss: 1.1810
Epoch 18/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8589 - attrition_output_loss: 0.3662 - department_output_accuracy: 0.6577 - department_output_loss: 0.7528 - loss: 1.1190 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3841 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7984 - val_loss: 1.1805
Epoch 19/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8330 - attrition_output_loss: 0.3897 - department_output_accuracy: 0.6371 - department_output_loss: 0.7934 - loss: 1.1833 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3823 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7977 - val_loss: 1.1779
Epoch 20/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - attrition_output_accuracy: 0.8381 - attrition_output_loss: 0.3657 - department_output_accuracy: 0.6521 - department_output_loss: 0.7703 - loss: 1.1357 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3812 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7976 - val_loss: 1.1768
Epoch 21/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - attrition_output_accuracy: 0.8435 - attrition_output_loss: 0.3717 - department_output_accuracy: 0.6589 - department_output_loss: 0.7754 - loss: 1.1473 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3823 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7963 - val_loss: 1.1766
Epoch 22/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - attrition_output_accuracy: 0.8460 - attrition_output_loss: 0.3596 - department_output_accuracy: 0.6445 - department_output_loss: 0.7689 - loss: 1.1284 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3812 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7969 - val_loss: 1.1762
Epoch 23/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - attrition_output_accuracy: 0.8609 - attrition_output_loss: 0.3427 - department_output_accuracy: 0.6516 - department_output_loss: 0.7701 - loss: 1.1131 - val_attrition_output_accuracy: 0.8688 - val_attrition_output_loss: 0.3814 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.7959 - val_loss: 1.1755
Epoch 24/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - attrition_output_accuracy: 0.8503 - attrition_output_loss: 0.3632 - department_output_accuracy: 0.6404 - department_output_loss: 0.7757 - loss: 1.1390 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3821 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7946 - val_loss: 1.1748
Epoch 25/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - attrition_output_accuracy: 0.8667 - attrition_output_loss: 0.3241 - department_output_accuracy: 0.6654 - department_output_loss: 0.7636 - loss: 1.0878 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3823 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7942 - val_loss: 1.1745
Epoch 26/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - attrition_output_accuracy: 0.8488 - attrition_output_loss: 0.3579 - department_output_accuracy: 0.6511 - department_output_loss: 0.7593 - loss: 1.1167 - val_attrition_output_accuracy: 0.8688 - val_attrition_output_loss: 0.3823 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7942 - val_loss: 1.1746
Epoch 27/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8580 - attrition_output_loss: 0.3412 - department_output_accuracy: 0.6558 - department_output_loss: 0.7738 - loss: 1.1155 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3829 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7933 - val_loss: 1.1743
Epoch 28/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8632 - attrition_output_loss: 0.3409 - department_output_accuracy: 0.6891 - department_output_loss: 0.7175 - loss: 1.0584 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3840 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7952 - val_loss: 1.1772
Epoch 29/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8734 - attrition_output_loss: 0.3334 - department_output_accuracy: 0.6688 - department_output_loss: 0.7296 - loss: 1.0626 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3844 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7955 - val_loss: 1.1780
Epoch 30/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8607 - attrition_output_loss: 0.3473 - department_output_accuracy: 0.6734 - department_output_loss: 0.7431 - loss: 1.0902 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3841 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7956 - val_loss: 1.1778
Epoch 31/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8599 - attrition_output_loss: 0.3472 - department_output_accuracy: 0.6670 - department_output_loss: 0.7585 - loss: 1.1057 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3836 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7967 - val_loss: 1.1784
Epoch 32/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8662 - attrition_output_loss: 0.3228 - department_output_accuracy: 0.6394 - department_output_loss: 0.7666 - loss: 1.0895 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3848 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.7963 - val_loss: 1.1791
Epoch 33/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8580 - attrition_output_loss: 0.3364 - department_output_accuracy: 0.6604 - department_output_loss: 0.7517 - loss: 1.0882 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3847 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7976 - val_loss: 1.1804
Epoch 34/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8885 - attrition_output_loss: 0.2952 - department_output_accuracy: 0.6762 - department_output_loss: 0.7333 - loss: 1.0284 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3857 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7967 - val_loss: 1.1804
Epoch 35/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8718 - attrition_output_loss: 0.3411 - department_output_accuracy: 0.6749 - department_output_loss: 0.7168 - loss: 1.0578 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3851 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7984 - val_loss: 1.1816
Epoch 36/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8660 - attrition_output_loss: 0.3347 - department_output_accuracy: 0.6826 - department_output_loss: 0.7029 - loss: 1.0374 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3848 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.8004 - val_loss: 1.1832
Epoch 37/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8863 - attrition_output_loss: 0.3048 - department_output_accuracy: 0.6668 - department_output_loss: 0.7197 - loss: 1.0243 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3862 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7996 - val_loss: 1.1839
Epoch 38/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8603 - attrition_output_loss: 0.3424 - department_output_accuracy: 0.6422 - department_output_loss: 0.7430 - loss: 1.0852 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3852 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.8005 - val_loss: 1.1837
Epoch 39/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8728 - attrition_output_loss: 0.3335 - department_output_accuracy: 0.6399 - department_output_loss: 0.8076 - loss: 1.1416 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3870 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.7987 - val_loss: 1.1840
Epoch 40/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8614 - attrition_output_loss: 0.3395 - department_output_accuracy: 0.6200 - department_output_loss: 0.7965 - loss: 1.1361 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3855 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.8019 - val_loss: 1.1854
Epoch 41/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8624 - attrition_output_loss: 0.3287 - department_output_accuracy: 0.6547 - department_output_loss: 0.7328 - loss: 1.0611 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3859 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.8031 - val_loss: 1.1872
Epoch 42/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8703 - attrition_output_loss: 0.3328 - department_output_accuracy: 0.6411 - department_output_loss: 0.7600 - loss: 1.0930 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3846 - val_department_output_accuracy: 0.6380 - val_department_output_loss: 0.8031 - val_loss: 1.1858
Epoch 43/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8709 - attrition_output_loss: 0.3227 - department_output_accuracy: 0.6685 - department_output_loss: 0.7225 - loss: 1.0449 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3852 - val_department_output_accuracy: 0.6561 - val_department_output_loss: 0.8038 - val_loss: 1.1872
Epoch 44/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8746 - attrition_output_loss: 0.3199 - department_output_accuracy: 0.6602 - department_output_loss: 0.7563 - loss: 1.0758 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3847 - val_department_output_accuracy: 0.6425 - val_department_output_loss: 0.8044 - val_loss: 1.1872
Epoch 45/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8618 - attrition_output_loss: 0.3219 - department_output_accuracy: 0.6710 - department_output_loss: 0.6977 - loss: 1.0194 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3845 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.8050 - val_loss: 1.1877
Epoch 46/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8664 - attrition_output_loss: 0.3239 - department_output_accuracy: 0.6694 - department_output_loss: 0.7298 - loss: 1.0533 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3832 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.8054 - val_loss: 1.1868
Epoch 47/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8780 - attrition_output_loss: 0.3222 - department_output_accuracy: 0.6681 - department_output_loss: 0.7224 - loss: 1.0450 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3838 - val_department_output_accuracy: 0.6425 - val_department_output_loss: 0.8079 - val_loss: 1.1901
Epoch 48/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8772 - attrition_output_loss: 0.3147 - department_output_accuracy: 0.6662 - department_output_loss: 0.7173 - loss: 1.0322 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3838 - val_department_output_accuracy: 0.6561 - val_department_output_loss: 0.8064 - val_loss: 1.1887
Epoch 49/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8512 - attrition_output_loss: 0.3320 - department_output_accuracy: 0.6646 - department_output_loss: 0.7199 - loss: 1.0520 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3833 - val_department_output_accuracy: 0.6425 - val_department_output_loss: 0.8084 - val_loss: 1.1900
Epoch 50/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8638 - attrition_output_loss: 0.3492 - department_output_accuracy: 0.6588 - department_output_loss: 0.7143 - loss: 1.0636 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3828 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.8086 - val_loss: 1.1898
Epoch 51/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8723 - attrition_output_loss: 0.3118 - department_output_accuracy: 0.6949 - department_output_loss: 0.7073 - loss: 1.0189 - val_attrition_output_accuracy: 0.8643 - val_attrition_output_loss: 0.3846 - val_department_output_accuracy: 0.6516 - val_department_output_loss: 0.8102 - val_loss: 1.1933
Epoch 52/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8826 - attrition_output_loss: 0.3015 - department_output_accuracy: 0.6691 - department_output_loss: 0.7144 - loss: 1.0159 - val_attrition_output_accuracy: 0.8597 - val_attrition_output_loss: 0.3837 - val_department_output_accuracy: 0.6471 - val_department_output_loss: 0.8100 - val_loss: 1.1921
Epoch 53/100

In [30]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'department_output': encoded_y_dep_test, 'attrition_output': encoded_y_att_test})
test_results

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8501 - attrition_output_loss: 0.3803 - department_output_accuracy: 0.6095 - department_output_loss: 0.8635 - loss: 1.2422

[1.3157036304473877,
 0.8907921314239502,
 0.4356098175048828,
 0.8396739363670349,
 0.595108687877655]

In [32]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {test_results[3]}")
print(f"Attrition Accuracy: {test_results[4]}")

Department Accuracy: 0.8396739363670349
Attrition Accuracy: 0.595108687877655

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. accuracy seems like it would be the best metric
2. Softmax for the department output due to having 3 outputs, and sigmoid for the attrition because it's binary.
3. more data.